services:
  api:
    build: .docker/php
    container_name: php-vue-api
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=docker
      - DATABASE_HOST=db
      - DATABASE_NAME=php_vue_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=A_1234567
    depends_on:
      - db
    networks:
      - app

  db:
    build: .docker/mysql
    container_name: php-vue-db
    restart: always
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
      - "./App/Models/sample_db.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: A_1234567
      MYSQL_DATABASE: php_vue_db
    ports:
      - "3306:3306"
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin
    container_name: php-vue-myadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=A_1234567
    depends_on:
      - db
    networks:
      - app

networks:
  app:
    driver: bridge
